[build]
  # Publish directory (current directory since files are in root)
  publish = "."
  
  # No build command needed for static site
  command = ""

# Redirect API calls to backend (update with your actual backend URL)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/webhook/*"
  to = "https://your-backend-url.railway.app/webhook/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://your-backend-url.railway.app/auth/:splat"
  status = 200
  force = true

# SPA fallback for any unmatched routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment variables for build
[build.environment]
  NODE_VERSION = "18"
